\global:
  enabled: true
  name: consul
  datacenter: dc1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
server:
  enabled: true
  replicas: 3
ui:
  enabled: true
  service:
    type: LoadBalancer
connectInject:
  enabled: true