kumuluzee:
  name: orders-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/OrdersDS
      connection-url: jdbc:postgresql://localhost:5432/orders
      username: dbuser1
      password: postgres1
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/OrdersDS
    metrics:
      web-instrumentation:
        - name: orders-endpoint
          url-pattern: /v1/order/*
rest-properties:
  maintenance-mode: false
  broken: false